variables:
  FRONTEND_TAG_LATEST: $CI_REGISTRY_IMAGE/frontend:latest
  BACKEND_TAG_LATEST: $CI_REGISTRY_IMAGE/backend:latest

stages:
  - build
  - first-test
  - second-test
  - deploy

build-job:
  stage: build
  image: docker:latest
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - echo "Building is ok!"

test-job1:
  stage: first-test
  image: docker:latest
  script:
    - echo "This job tests something"

test-job2:
  stage: second-test
  image: docker:latest
  script:
    - echo "This job tests something more"
    - sleep 10
    - echo "You see this after 10 seconds"
    - echo "You see an error \/"
    - echo ";jngw;e"

deploy-prod:
  stage: deploy
  image: docker:latest
  script:
    - echo "This deploys from the $GIT_COMMIT_BRANCH branch."
  environment: production